apiVersion: v2
name: controlplane-operations
version: 1.0.10
description: A set of Plutono dashboards and Prometheus alerting rules combined with playbooks to ensure effective operations of Controlplane clusters.
maintainers:
  - name: Vladimir Videlov (d051408)
    email: vladimir.videlov@sap.com
keywords:
  - Helm Chart
  - Controlplane operations
  - Plutono Dashboards
  - Prometheus Alerting
  - Alert Rules
  - Playbooks
